version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing frontend dependencies"
      - npm install
  build:
    commands:
      - echo "Building frontend"
      - npm run build
  post_build:
    commands:
      - echo "Post build phase"
      # - mkdir -p /tmp/deployment/frontend
      # - echo "Copying build files to /tmp/deployment/frontend"
      # - cp -R dist/* /tmp/deployment/frontend/
      # - echo "Listing contents of /tmp/deployment/frontend"
      # - ls -la /tmp/deployment/frontend

artifacts:
  # include all files required to run application
  # notably excluded is node_modules, as this will cause overwrite error on deploy
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appsec.yml
    - scripts/**/*