version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - echo "Installing dependencies"
            - npm install
    pre_build:
        commands: 
            - echo "We are in the pre-build phase"
    build:
        commands:
            - echo "We are in the build block"
            - echo "We will run some tests"
            - npm run build

artifacts:
  # include all files required to run application
  # notably excluded is node_modules, as this will cause overwrite error on deploy
  files:
    - public/**/*
    - src/**/*
    - package.json
    - server.js
    - appspec.yml
    - scripts/**/*
