version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing frontend dependencies"
      - npm install
  build:
    commands:
      - echo "Building frontend"
      - npm run build
  post_build:
    commands:
      - echo "Post build phase"
      - mkdir /tmp/deployment/frontend
      - cp -R build/* /tmp/deployment/frontend/

artifacts:
  files:
    - /tmp/deployment/frontend/**/*